@LearningAPI_HostAddress = https://localhost:7004

GET {{LearningAPI_HostAddress}}/tutorial?search=my

###

POST {{LearningAPI_HostAddress}}/tutorial
Content-Type: application/json

{
 "title": "Web API",
 "description": "Happy coding :)"
}


###
